### ISSUE TITLE
Consider describing changes first before replacement

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-rest-client-async#24]
Users are asked to replace the content of the files first before the changes are described.  Once replaced, it will be harder for users to do a compare and contrast between the before and after.  Consider describing the changes -- at least, summarizing -- before the replacement instruction.

This is a nice-to-have suggestion can be handled later.

**Comment by evelinec** [comment]
@yeekangc noticed you had made some changes to the statement. Thank you. Do you think the feedback/suggestion is fully addressed now? If not, the issue is to be assigned to @jonathanxue. Thanks.
