### ISSUE TITLE
End-to-end Linux test errors

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-microprofile-rest-client-async#28]
System specs:
![image](https://user-images.githubusercontent.com/26514093/64815618-ff23c380-d573-11e9-80d2-2db6e91d5813.png)

Building and running the application
---
![image](https://user-images.githubusercontent.com/26514093/64815500-b66c0a80-d573-11e9-9917-5a7b53503b70.png)

Running the `curl` commands on a Linux system produces the following error:

![image](https://user-images.githubusercontent.com/26514093/64815544-d26fac00-d573-11e9-8b98-e21f66eae507.png)

**Comment by MaiHameed** [comment]
The server starts, then after a few moments it disappears... and when I run the `curl` command when the server was running, I got the following response that differs from the JSON formatted expected response as shown in the guide:
![image](https://user-images.githubusercontent.com/26514093/64866204-f7622e80-d608-11e9-9717-c4bbee12ff8a.png)

**Comment by evelinec** [comment]
@MaiHameed can you assess whether this issue still exist?
