### ISSUE TITLE
Review class names

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-rest-client-async#30]
- Review class names and consider names that describe the purpose of the classes without ambiguity -- e.g. JobGatewayClient can be interpreted as a client to access the job gateway, which doesn't exist -- while at the same time avoid duplicate class names.

- Review and update guide where appropriate to use updated class names and use consistent names/terms to describe the same entity throughout.

- Review section titles accordingly for clarification too -- "Changing the template interface to use asynchronous methods" refers to changes on the client side while "Responding asynchronously to an HTTP request" is on the service side.

**Comment by jonathanxue** [comment]
For the class names, I'm not sure if there's a way to rename them to be specific, and at the same time not too long. Something like 'GatewayClientForJob' feels too clunky. The guide already includes clarifications for the role of these classes too, so I think it better to maybe just add a bit more clarification in the guide, and leave the names as they are.

**Comment by yeekangc** [comment]
The confusion comes with the use of "Gateway".  If we can think of alternate names without "Gateway" in them.  That would be a good start.

**Comment by evelinec** [comment]
Gateway is the name used in the BFF pattern: https://microservices.io/patterns/apigateway.html#variation-backends-for-frontends. `JobGatewayClient` is interpreted as the gateway client to access the `Job` service, perhaps we name it as `JobGatewayclient`? It was initially named as `JobClient` in the `gateway` service, but we also have a `JobClient` for the `job` service. So we thought it was appropriate to rename it as `JobGatewayClient`.

**Comment by yeekangc** [comment]
Yes, there is a gateway in a BFF pattern.  The BFF itself can be considered a gateway.

Then, the clients here aren't gateways themselves but REST clients to remote services that the gateway service is meant to be a gateway to.

That's what needs clarification.  Off the top of my head, an option is `JobServiceClient`.

Also, I wonder if the clients should be common across the services too.  Haven't looked and gave it much thought.

**Comment by evelinec** [comment]
I'm good with `JobServiceClient` as the client class name. @jonathanxue ^

**Comment by jonathanxue** [comment]
Would something like ```JobGatewayServiceClient``` be more precise? Then we know its strictly between the gateway and job micro services. I feel that ```JobServiceClient``` could also be misinterpreted for a client between the job and system

**Comment by yeekangc** [comment]
The client if it's done with MP Rest Client will map directly to the remote service that it should invoke.  Whether it's between job and gateway or job and system, the client to job should be the same?

**Comment by gkwan-ibm** [comment]
@jonathanxue 
- [ ] refactor the following:
  - InventoryGatewayClient -> InventoryClient
  - JobGatewayClient -> JobClient
  - InventoryGatewayResource -> GatewayInventoryResource
  - JobGatewayResource -> GatewayJobResource
- [ ] Update the README

**Comment by evelinec** [comment]
@gkwan-ibm `JobClient` and `InventoryClient` are what we had initially. There's a `JobClient` class in the `Job` service as well that causes confusion to users, see https://github.com/OpenLiberty/guide-microprofile-rest-client-async/issues/15.

**Comment by evelinec** [comment]
I'm good with the first 4 refactor/rename of the classes. What's the reason we are renaming the test classes?

**Comment by yeekangc** [comment]
IT is the default for integration tests for the failsafe plugin.  If I am not mistaken, this is clean-up to follow typical practices.  We will want to do the same for all guides too.
