### ISSUE TITLE
Inconsistencies with HTTP endpoints

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guide-microprofile-rest-client-async#48]
Some are hyperlinks and some are plain text.

![image](https://user-images.githubusercontent.com/33457590/77131936-f97fcc80-6a33-11ea-8d48-ded829412a9a.png)

**Comment by gkwan-ibm** [comment]
will be addressed by https://github.com/openliberty/guide-microprofile-rest-client-async/issues/49
- the table will be removed because of using the new app
