### ISSUE TITLE
Convert the guide to use OpenLibertyCafe app

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-rest-client-async#49]
Need to replace the app by the OpenLibertyCafe app and update the README

**Comment by gkwan-ibm** [comment]
Proposed flow:
- go to start directory
- build the app
- run the app
- inspect the order service messages.log
  - orders should be logging in sync
- stop the app
- update the OrderClient to use following to make the clients call async
  - @Asynchronous
  - CompletionStage<Response> createOrder(Order order);
- ???update the OpenLibertyCafeOrderResource.createOrder to sync the orderClient.createOrder(order) calls
- rebuild the app
- run the app
- inspect the order service messages.log
  - orders should be logging in async way
- stop the app
- remove testing

**Comment by gkwan-ibm** [comment]
tasks:
- [ ] create the app in start with
  - `Response createOrder(Order order);`
- [ ] prove the logs in the order service messages.log are in sync
- [ ] (Gilbert) investigate sync the code in `OpenLibertyCafeOrderResource.createOrder()`
- convert the guide
  - replace the app by OpenLibertyCafe app
    - [ ] in the finish directory
    - [ ] in the start directory
  - [ ] update the readme

**Comment by ankitagrawa** [comment]
- Application converted.
- Modifying the readme.

**Comment by gkwan-ibm** [comment]
- updated the readme
- setting the lgdev to review

**Comment by gkwan-ibm** [comment]
- **What you’ll learn**
  - [ ] waiter -> waitstaff
  - [ ] update the diagram from the reactive messaging guide
    - need to discuss the diagram is necessary or draw another focus on order and openLibertyCafe
  - [ ] "backends for frontends" -> "backend for frontend" 
  - [ ] no need the detail to explain the whole app
    - keep the paragraph "The microservice that you will modify is the OpenLibertyCafe service. ..." and add more to explain what'll do
- **Sending order requests synchronously**
  - [ ] "Running the synchronous application" -> "Running the application"
  - [ ] add a subsection "Trying the application" before "Once the application is up and running, ..."
  - [ ] update the order of "OpenLibertyCafe, Order, Bar, Kitchen, ServingWindow, and Status" alphabetically
  - [ ] update the order for `docker build ...` commands alphabetically
  - [ ] Need to ask readers to `startContainers.sh`
- **Updating a REST resource to asynchronously handle HTTP requests**
  - [ ] Need to explain `countdownLatch.await();`
- **Building and running the application**
  - [ ] because only updated the OpenLibertyCafe service, only need to ask reader to repackage it and rebuild the docker image

**Comment by gkwan-ibm** [comment]
- addressing the dev content review feedback

**Comment by gkwan-ibm** [comment]
- ready for dev content review
- need to address the auto test failure

**Comment by gkwan-ibm** [comment]
design changed so it will be addressed by #53
