### ISSUE TITLE
Convert the guide to use the new app from the reactive messaging guide

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-rest-client-async#53]
Need to replace the app by the new System/Inventory app, update the gateway service, and update the README

- [ ] dev mode
  - [ ] use the ideal(simplified) pom.xml
  - [ ] update the Readme content to use dev mode
    - [ ] keep the flow same (let discuss if the flow not work)
  - [x] convert *Test class to *IT
  - [x] convert to use JUnit 5
    - [x] use JUnit5 test order if need
  - [x] make sure to correctly configure the ports in test classes, server.xml, and pom.xml
  - [x] update travis test
    - [x] mvn install cannot be used to verify anymore
- [x] latest mp
- [x] latest plugin and dependencies versions
- [ ] jakartaee
- [x] ideal dockerfile
- [x] #27 (duplicate)
- [x] better remove JDK 9+ dependencies
  - https://github.com/OpenLiberty/guides-common/issues/459

**Comment by gkwan-ibm** [comment]
- have a new design for the app and revising the application

**Comment by gkwan-ibm** [comment]
- the app was completed
- updated the readme
- ready for dev content review

**Comment by gkwan-ibm** [comment]
peer review:
- [ ] Mac (Darren)
- [ ] Linux
- [ ] Window

**Comment by gkwan-ibm** [comment]
- peer review completed
- addressed SME feedback
- next ID review

**Comment by gkwan-ibm** [comment]
- ID review completed

**Comment by gkwan-ibm** [comment]
- need final approval from YK

**Comment by AustinSeto** [comment]
YK's comments
Issue: https://github.com/OpenLiberty/guide-microprofile-rest-client-async/issues/67
PR into QA branch: https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/68

**Comment by gkwan-ibm** [comment]
- addressed the ID review feedback and approved
- ready to publish

**Comment by yeekangc** [comment]
Providing final approval and signoff.  Please proceed with publishing.  Thank you, team.
