### ISSUE TITLE
Dev content review for updating the app

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-rest-client-async#61]
- [x] add "Additional prerequisites" section as the reactive messaging guide
- **What you’ll learn**
  - [x] The 2 paragraphs "The application that you’ll be working... The system microservice records ..." -> "The application in this guide consists of three microservices, `system`, `inventory`, and `query`. Every 15 seconds, the `system` microservice calculates and publishes an event that contains its current average system load. The `inventory` microservice subscribes to that information so that it can keep an updated list of all the systems and their current system loads." 
  - [x] The paragraph "The microservice that you will modify is the query service. It acts as a middleman..." -> "The microservice that you will modify is the `query` service. It communicates with the `inventory` service multiply to determine which system has the highest system load and which system has the lowest system load."
  - [x] "The application also uses the Apache Kafka and ZooKeeper services to distribute the job results and system status." -> "The `system` and `inventory` microservices uses MicroProfile Reactive Messaging to send and receive the system load events."
  - [x] The paragraph "If you want to learn more about MicroProfile Rest Client, ..." -> "If you want to learn more about reactive messaging, you can read the http://...[Creating reactive Java microservices^] guide.
- **Updating the template interface of a REST client to use asynchronous methods**
  - [x] add hotspot to `@Asynchronous`
  - [x] "...manipulate the inner `Properties`" -> "manipulate the inner type `Properties`"
  - [x] paragraph "The keyword volatile and ..." -> like "By declaring the `values` variable with [hotspot]`volatile` and instantiating as a [hotspot]`ConcurrentHashMap`, both allows the `values` variable to store system information and to be safely accessed asynchronously by multiple threads."
- **Building and running the application**
  - [x] "...query, system, and inventory ..." -> "...system, inventory, and query ..."
  - [x] use the same instruction from the reactive message guide to build the app instead of using scripts except startContainers, because using os tabs is a bit complicated 
      - can keep the scripts but not ask readers to use it
- "**Tearing down the environment**"
  - [x] remove this section and move the content at the end of the "Building and running the application" section
  - [x] remove "Navigate back to the start directory."
  - [x] change to "When you are done checking out the application, run the following script to stop the application:"
- **Testing the query application**
  - [x] "Testing the query application" -> "Testing the query microservice"

**Comment by AustinSeto** [comment]
Changes made in `app-replacement` branch and pushed to lgdev site

**Comment by gkwan-ibm** [comment]
- **What you’ll learn**
  - [ ] the diagram is too big, need to improve it
  - [ ] remove "in the `start/src` directory."
  - [ ] combine the paragraph "If yoy want to learn..." to the above paragraph.
- **Building and running the application**
  - [ ] remove statement "Install Docker by ...." because added the additional prereq section
  - [ ] the qurey command is wrong under "Run the following commands to containerize the microservices:"
- [ ] format the QueryServiceIT.java better so that no wrapped line

**Comment by AustinSeto** [comment]
Changes made in `app-replacement` branch and pushed to lgdev site
