### ISSUE TITLE
Peer Review - Windows

### ISSUE THREAD

**Issue by TiagoF99** [OpenLiberty/guide-microprofile-rest-client-async#62]
Functionality
---
- [ ] Check that the guide has working instructions and sample code
- [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---

`README.adoc` checks:
- [ ] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
- [ ] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [ ] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [ ] Check that the pom.xml, server.xml, etc files are clean
    - [ ] Remove any dependencies and features that are not required
    - [ ] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
- [ ] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided

`pom.xml` checks (if files are present):
- [ ] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/master/finish/pom.xml
- [ ] Check that the following dependencies are included in all of the `pom.xml` files:
```
<!-- Provided dependencies -->
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId
  <artifactId>microprofile</artifactId>
  <version>3.3</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```
- [ ]  Check that the versions of plugins are directly provided and not fed in by a file property.
  - Not formatted like so:
```
    <properties>
        <!-- Plugins -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
    </properties>

    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>${version.liberty-maven-plugin}</version>
    </plugin>
```
  - Should be formatted like so:
```
    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.2</version>
    </plugin>
```
- [ ] Check that there are 4 spaces per indent for proper formatting
- [ ] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable

Overall checks:
- [ ] Check the consistency of guide with the template and other guides
- [ ] Check the quality of code according to the best coding practices
- [ ] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
- [ ] Check that the directories are properly structured
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

---

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [ ] Check the appearance of the guide on test site for the following items: 
    - [ ] Table of contents 
    - [ ] Headings
    - [ ] Paragraphs
    - [ ] code snippets
    - [ ] outputs
    - [ ] links
    - [ ] hotspots 
- [ ] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by TiagoF99** [comment]
**Updating a REST resource to asynchronously handle HTTP requests**
- [ ] ```JAX-RS resources can also have asynchronous methods. So instead of returning a Properties type, you can return a CompletionStage<Properties> type.``` should maybe be: ```JAX-RS resources can also have asynchronous methods. Therefore, you can return a CompletionStage<Properties> type instead of a Properties type```
**Building and Running the application**
- [ ] this command ```docker exec -it inventory cat /logs/messages.log``` just is very confusing. It gives a whole bunch of logs and gives the expected result outlined in the guide but after a bunch of random lines. It may confuse the user and they spend alot of time reading this output to find the result which seems unnecessary.  I think it would make more sense to just ask them to visit the endpoint or to use the curl command and look for the desired output similar to: 
```
{
    "highest": {
        "hostname" : "8841bd7d6fcd",
        "systemLoad" : 6.96
    },
    "lowest": {
        "hostname" : "37140ec44c9b",
        "systemLoad" : 6.4
    }
}
```
As reference, heres the output of the command:
<img width="1440" alt="Screen Shot 2020-06-24 at 10 23 05 AM" src="https://user-images.githubusercontent.com/45250015/85574507-d81b1780-b604-11ea-9834-f5bc80cdcd82.png">
- [ ] ```In the /query/systemLoad endpoint multiple systems are read and compared at once.``` should have a comma after 'endpoint'.

**Comment by TiagoF99** [comment]
Due to issues with running docker on a windows VM, Danny will be running a quick e2e for the guide on his windows machine to verify it works.

**Comment by AustinSeto** [comment]
Updated wording to "JAX-RS resources can also have asynchronous methods. These would return a CompletionStage<Properties> type instead of a Properties type." as discussed on Slack.

Changed service availability check to just tell user that service is available once endpoint output is non-empty and wait and check until it is

Punctuation fix made

Checked pom files, microprofile dependency is after jakarta dependency in all applicable pom files

**Comment by TiagoF99** [comment]
**Building and running the application**
- [ ] ```Output will be empty until the service is available. This normally takes a few minutes.```. I think this is redundant as it is mentioned in the previous paragraph

**Comment by AustinSeto** [comment]
Redundant paragraph removed

**Comment by TiagoF99** [comment]
feedback addressed. Closing issue now.
