### ISSUE TITLE
Align with Rest Client 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-rest-client-async#93]
Update this guide to use MP Rest Client 2.0, which will be part of MP 4.0

**Comment by gkwan-ibm** [comment]
only update the pom.xml and server.xml to latest versions

**Comment by gkwan-ibm** [comment]
close
- the [guide](https://openliberty.io/guides/microprofile-rest-client-async.html) was updated
